# Generated by Django 2.1.5 on 2019-01-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_str', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'send_str',
            },
        ),
    ]
